"""add_user_role_column

Revision ID: 6bd091d30152
Revises: 27c7fe7620a7
Create Date: 2026-06-02 17:35:27.097473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd091d30152'
down_revision: Union[str, Sequence[str], None] = '27c7fe7620a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum('admin', 'editor', 'user', name='user_role', create_constraint=True)
    user_role.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', user_role, server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE IF EXISTS user_role")
    # ### end Alembic commands ###
