// AUTO-GENERATED by make generate. Do not edit directly.
// Modify Pydantic models in packages/shared-py/src/starter_shared/types/
// and run `make generate` to regenerate.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Status = string;
export type Version = string;
export type Database = string;

/**
 * Health check response model.
 *
 * This model is exported to TypeScript via the type bridge.
 * It serves as a simple verification that the entire pipeline works.
 */
export interface HealthCheck {
  status?: Status;
  version?: Version;
  database?: Database;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Email = string;
export type Password = string;
export type Name = string;

/**
 * Schema for user registration requests.
 */
export interface UserCreate {
  email: Email;
  password: Password;
  name: Name;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


/**
 * Schema for user login requests.
 */
export interface UserLogin {
  email: Email;
  password: Password;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
/**
 * User role for access control.
 */
export type UserRole = "admin" | "editor" | "user";
export type CreatedAt = string;

/**
 * Schema for user data returned in API responses.
 *
 * Never includes the hashed password.
 */
export interface UserResponse {
  id: Id;
  email: Email;
  name: Name;
  role?: UserRole;
  created_at: CreatedAt;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AccessToken = string;
export type RefreshToken = string;
export type TokenType = string;

/**
 * Schema for JWT token pairs returned after login/register/refresh.
 */
export interface TokenResponse {
  access_token: AccessToken;
  refresh_token: RefreshToken;
  token_type?: TokenType;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


/**
 * Schema for forgot-password requests.
 */
export interface ForgotPassword {
  email: Email;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Token = string;
export type NewPassword = string;

/**
 * Schema for reset-password requests.
 */
export interface ResetPassword {
  token: Token;
  new_password: NewPassword;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


/**
 * Schema for updating user profile (name only for now).
 */
export interface UserUpdate {
  name: Name;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OldPassword = string;

/**
 * Schema for changing the user's password.
 */
export interface PasswordChange {
  old_password: OldPassword;
  new_password: NewPassword;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User role for access control.
 */

/**
 * Schema for updating a user's role (admin only).
 */
export interface UserRoleUpdate {
  role: UserRole;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User role for access control.
 */

/**
 * Schema for admin creating a new user account.
 */
export interface AdminUserCreate {
  email: Email;
  password: Password;
  name: Name;
  role?: UserRole;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


/**
 * Schema for admin resetting a user's password directly.
 */
export interface AdminResetPassword {
  new_password: NewPassword;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User role for access control.
 */

/**
 * Schema for admin editing a user's profile (name, email, role).
 */
export interface UserUpdateAdmin {
  name: Name;
  email: Email;
  role: UserRole;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TotalUsers = number;
export type AdminCount = number;
export type EditorCount = number;
export type UserCount = number;
export type RecentRegistrations = number;

/**
 * Schema for admin dashboard statistics.
 */
export interface DashboardStats {
  total_users: TotalUsers;
  admin_count: AdminCount;
  editor_count: EditorCount;
  user_count: UserCount;
  recent_registrations: RecentRegistrations;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User role for access control.
 */
export type Items = UserResponse[];
export type Total = number;
export type Skip = number;
export type Limit = number;

/**
 * Schema for paginated user list responses.
 */
export interface PaginatedUserResponse {
  items: Items;
  total: Total;
  skip: Skip;
  limit: Limit;
}
/**
 * Schema for user data returned in API responses.
 *
 * Never includes the hashed password.
 */
export interface UserResponse {
  id: Id;
  email: Email;
  name: Name;
  role?: UserRole;
  created_at: CreatedAt;
}
