#!/usr/bin/env python3
"""Type bridge: generate TypeScript types from Pydantic models.

Reads Pydantic models defined in packages/shared-py/src/starter_shared/types/,
converts them to JSON Schema, then generates TypeScript interfaces using
json-schema-to-typescript (Node.js CLI).

Only models in the EXPORT_MODELS whitelist are exported to TypeScript.
Internal models (database, security) are never exposed to the frontend.

Usage:
    python scripts/generate_types.py
    make generate
"""

import importlib
import json
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Whitelist: only these models are exported to TypeScript.
# Add new models here when you create them.
# Format: "module_path:ModelName"
# ---------------------------------------------------------------------------
EXPORT_MODELS: list[str] = [
    "starter_shared.types.health:HealthCheck",
    "starter_shared.types.user:UserCreate",
    "starter_shared.types.user:UserLogin",
    "starter_shared.types.user:UserResponse",
    "starter_shared.types.user:TokenResponse",
    "starter_shared.types.user:ForgotPassword",
    "starter_shared.types.user:ResetPassword",
    "starter_shared.types.user:UserUpdate",
    "starter_shared.types.user:PasswordChange",
    "starter_shared.types.user:UserRoleUpdate",
    "starter_shared.types.user:AdminUserCreate",
    "starter_shared.types.user:UserUpdateAdmin",
    "starter_shared.types.admin:DashboardStats",
    "starter_shared.types.admin:PaginatedUserResponse",
]

# Paths
REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED_TS_TYPES_DIR = REPO_ROOT / "packages" / "shared-ts" / "src" / "types"
SHARED_TS_INDEX = SHARED_TS_TYPES_DIR / "index.ts"


def resolve_model(spec: str) -> tuple[type, str]:
    """Import a Pydantic model from a 'module.path:ModelName' spec."""
    module_path, model_name = spec.rsplit(":", 1)
    module = importlib.import_module(module_path)
    model_cls = getattr(module, model_name)
    return model_cls, model_name


def generate_json_schema(model_cls: type, model_name: str) -> dict:
    """Generate JSON Schema from a Pydantic model."""
    schema = model_cls.model_json_schema()
    # Add $id for better type naming
    schema["$id"] = f"#/definitions/{model_name}"
    schema["title"] = model_name
    return schema


def json_schema_to_typescript(schema: dict, model_name: str) -> str:
    """Convert a single JSON Schema to TypeScript using json-schema-to-typescript CLI.

    Calls npx json-schema-to-typescript via subprocess.
    Each model is processed individually so the generated type name matches.
    """
    tmp_schema = REPO_ROOT / f".tmp-schema-{model_name}.json"
    tmp_schema.write_text(json.dumps(schema, indent=2))

    try:
        result = subprocess.run(
            [
                "npx",
                "json-schema-to-typescript",
                "--input", str(tmp_schema),
                "--cwd", str(REPO_ROOT),
                "--style", "single-quote",
                "--no-custom-header",
            ],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
        )

        if result.returncode != 0:
            print(f"ERROR: json-schema-to-typescript failed:", file=sys.stderr)
            print(result.stderr, file=sys.stderr)
            sys.exit(1)

        return result.stdout

    finally:
        if tmp_schema.exists():
            tmp_schema.unlink()


def main() -> None:
    """Run the type bridge generation pipeline."""
    print("Type bridge: generating TypeScript types from Pydantic models...")

    # Ensure output directory exists
    SHARED_TS_TYPES_DIR.mkdir(parents=True, exist_ok=True)

    # Step 1: Collect JSON Schemas from whitelisted models
    schemas: dict[str, dict] = {}
    for spec in EXPORT_MODELS:
        model_cls, model_name = resolve_model(spec)
        schema = generate_json_schema(model_cls, model_name)
        schemas[model_name] = schema
        print(f"  Collected schema: {model_name}")

    # Step 2: Convert each model to TypeScript individually
    all_ts_parts: list[str] = []
    for model_name, schema in schemas.items():
        ts_output = json_schema_to_typescript(schema, model_name)
        all_ts_parts.append(ts_output)
        print(f"  Generated TS: {model_name}")

    # Step 3: Write combined output (deduplicate type aliases)
    generated_file = SHARED_TS_TYPES_DIR / "generated.ts"
    header = (
        "// AUTO-GENERATED by make generate. Do not edit directly.\n"
        "// Modify Pydantic models in packages/shared-py/src/starter_shared/types/\n"
        "// and run `make generate` to regenerate.\n\n"
    )
    import re

    _TYPE_ALIAS_RE = re.compile(r"^export type (\w+) = ", re.MULTILINE)
    seen_aliases: set[str] = set()
    deduped_parts: list[str] = []

    for part in all_ts_parts:
        # Find all type aliases in this part
        aliases_in_part = set(_TYPE_ALIAS_RE.findall(part))
        # Remove aliases we've already seen
        for alias in aliases_in_part:
            if alias in seen_aliases:
                # Remove the duplicate line
                part = re.sub(
                    rf"^export type {alias} = [^\n]+\n", "", part, flags=re.MULTILINE
                )
            seen_aliases.add(alias)
        deduped_parts.append(part)

    combined = "\n".join(deduped_parts)
    # Remove `[k: string]: unknown;` lines — they cause duplicate index
    # signature errors when interfaces reference each other (e.g. PaginatedUserResponse → UserResponse[])
    combined = re.sub(r"^\s*\[k: string\]: unknown;\n", "", combined, flags=re.MULTILINE)

    generated_file.write_text(header + combined)
    print(f"  Written: {generated_file.relative_to(REPO_ROOT)}")

    # Step 4: Update the barrel index.ts to re-export generated types
    re_exports = []
    for spec in EXPORT_MODELS:
        _, model_name = spec.rsplit(":", 1)
        re_exports.append(f'export type {{ {model_name} }} from "./generated.js";')

    index_content = (
        "// Auto-generated barrel file. Re-runs on `make generate`.\n\n"
        + "\n".join(re_exports)
        + "\n"
    )
    SHARED_TS_INDEX.write_text(index_content)
    print(f"  Updated: {SHARED_TS_INDEX.relative_to(REPO_ROOT)}")

    print(f"Type bridge: done. {len(schemas)} model(s) exported.")


if __name__ == "__main__":
    main()
